<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-8VUSPTS" failures="1" tests="16" name="TestCases.TestExecution" time="6.275" errors="0" timestamp="2024-11-29T15:50:32 EET" skipped="0">
  <testcase classname="TestCases.TestExecution" name="TC5" time="0.016"/>
  <testcase classname="TestCases.TestExecution" name="TC7" time="0.270"/>
  <testcase classname="TestCases.TestExecution" name="TC9" time="0.065"/>
  <testcase classname="TestCases.TestExecution" name="TC6" time="0.028"/>
  <testcase classname="TestCases.TestExecution" name="TC1" time="0.168"/>
  <testcase classname="TestCases.TestExecution" name="TC4" time="0.253"/>
  <testcase classname="TestCases.TestExecution" name="TC11" time="0.021"/>
  <testcase classname="TestCases.TestExecution" name="TC14" time="0.159"/>
  <testcase classname="TestCases.TestExecution" name="TC13" time="0.532"/>
  <testcase classname="TestCases.TestExecution" name="TC12" time="0.479"/>
  <testcase classname="TestCases.TestExecution" name="TC15" time="0.207"/>
  <testcase classname="TestCases.TestExecution" name="TC2" time="0.169"/>
  <testcase classname="TestCases.TestExecution" name="TC8" time="0.255"/>
  <testcase classname="TestCases.TestExecution" name="TC3" time="0.271"/>
  <testcase classname="TestCases.TestExecution" name="TC10" time="3.292"/>
  <testcase classname="TestCases.TestExecution" name="TC16" time="0.090">
    <failure message="expected [1Thank you for your order!] but found [Thank you for your order!]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1Thank you for your order!] but found [Thank you for your order!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at TestCases.TestExecution.TC16(TestExecution.java:142)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC16 -->
</testsuite> <!-- TestCases.TestExecution -->
